### ISSUE TITLE
cooler supporting 5C data

### ISSUE THREAD

**Issue by sergpolly** [mirnylab/cooler#104]
@nvictus what is the current state of the support for the 5C type of data in `cooler`?
Is the 5C support on the `cooler` development roadmap?

My understanding of the problem is limited at the moment, but @betulakgol PhD student in the Lab is trying to find workarounds to make 5C data work with cooler and eventually HiGlass.
From our perspective it seems like supporting gaps in bins-layout has the highest priority for now ...
Such that list of bins like that is a valid bin-layout:
```
chr1	30000	45000
chr1	45000	60000
chr1	60000	75000
chr1	75000	90000
chr1	90000	105000
chr1	183000	198000
chr1	198000	213000
chr1	213000	228000
```
Given the 5C experiment was done on regions `chr1:30000-90000` and then `chr1:183000-228000`.

Just in case, this is a collection of issues that seems related to application of `cooler` to 5C type of data:
https://github.com/mirnylab/cooler/issues/98
https://github.com/mirnylab/cooler/issues/84
https://github.com/mirnylab/cooler/issues/81
https://github.com/mirnylab/cooler/issues/80

**Comment by nvictus** [comment]
The bin table currently is supposed to house a complete genomic segmentation of the scaffolds being used. 

Can you better explain the rationale for leaving those regions out? Because we lose information about where the probes are? Or is it just ugly if the gap regions appear as interleaving blank bins in the matrix? I think it may be possible to drop them, but we'd need to think about whether making the gaps implicit would break any assumptions in the way cooler does things.

Bins cost relatively little to store, and the number of pixels would be the same in either case.

I imagine it's cumbersome to do dense queries on a 5C dataset? I can think of a couple workarounds for now using `c.matrix(sparse=True)` or `c.matrix(as_pixels=True)`.

**Comment by sergpolly** [comment]
After a discussion with @betulakgol, I guess, I can reformulate a 5C-adapted binning example this way:
```
chr1	0	30000
chr1	30000	45000
chr1	45000	60000
chr1	60000	75000
chr1	75000	90000
chr1	90000	105000
chr1	105000	183000
chr1	183000	198000
chr1	198000	213000
chr1	213000	228000
chr1	213000	100000000
```
, where `100000000` is the size of the `chr1` and  5C experiment was done for regions `chr1:30000-90000` and  `chr1:183000-228000`, and bin size for the meaningful region being `15kb`.

in contrast, the default cooler binning would yield:
```
chr1	0	15000
chr1	15000	30000
chr1	30000	45000
chr1	45000	60000
chr1	60000	75000
chr1	75000	90000
chr1	90000	105000
chr1	105000	120000
chr1	120000	135000
chr1	135000	150000
chr1	150000	165000
...```

and thought forcing 5C data into a bins like that is possible, it's far from perfect. @betulakgol , please, correct me if I misunderstood something.

**Comment by nvictus** [comment]
This already works for cooler, but not HiGlass yet. Just provide the bin table as a BED file to the creation command (`cooler load` or `cooler cload`) or as a dataframe to the creation function (`create()` or `create_from_unordered()`)

To be honest, I think you might even be able to leave out the gap bins and it might just work! Never tested it, but I don't think any internal logic relies on the fact that bins are contiguous. It does require, however, that they are non-overlapping and monotonically increasing.

**Comment by betulakgol** [comment]
Hi Nezar,

Thank you for your input. I created .cool file using cooler load with
bedgraph-like input . Using cooler show I was able to see the five 5C
regions that I have mapped reads. However, when I created the .mcool file
and upload it to Higlass I was able to see only one of the 5C regions on
chromosome 1. It looked like the other regions did not have any data. Here
is the dropbox link for the files :

https://www.dropbox.com/sh/iamzy2x9bb2sdqq/AADDaGVvB6ZNL5MZN9z0rZSMa?dl=0

I used the commands below:

cooler load --count-as-float --tril-action drop --assembly hg19 --format
bg2 chrom.sizes.txt:1875 input output.cool
cooler zoomify --no-balance output.cool
cooler show --zmin='0.0' --zmax='1.0' -o output1 output.cool
chr11:100,839,375-101,435,957


Thank you so much for your help!

Best,
Betul

2018-03-19 17:01 GMT-04:00 Nezar Abdennur <notifications@github.com>:

**Comment by nvictus** [comment]
Hi Betul,

It looks like all your regions are there, they just aren't where you expect. It's because currently the chrom sizes you use in the cooler need to match what higlass expects, or else you need to upload a different coordinate system to higlass and use it instead. 

Try reloading your coolers with [this](https://raw.githubusercontent.com/pkerpedjiev/negspy/master/negspy/data/hg19/chromSizes.tsv) chromsizes file. e.g. 

```bash
cooler dump --join <input>.cool | cooler load -f bg2 --count-as-float hg19.chrom.sizes:1875 - <output>.cool
```

**Comment by betulakgol** [comment]
It worked. Thank you very much for your help!

Best,
Betul

2018-06-04 19:01 GMT-04:00 Nezar Abdennur <notifications@github.com>:
