### ISSUE TITLE
[Discussion] Datatype of field 'count' in matrix

### ISSUE THREAD

**Issue by joachimwolff** [mirnylab/cooler#108]
A general question: How strict is the usage of the datatypes you have defined? In you documentation on readthedocs it is written that the datatype of matrix['count'] is a int32 (http://cooler.readthedocs.io/en/latest/schema.html#contact-matrix). You can manipulate this by setting `cooler._writer.COUNT_DTYPE ` to another datatype, but this is non-standard behaviour. The usage of int32 as a datatype is a bit problematic because after a correction of a transformation of the data to obs/exp or pearson matrix we need float values and not integers. For this case you have the field 'weight' in bins and the idea is to apply this weights to the int counts. 
I see here two issues: 1. It is a slow down factor to apply every time the correction factors instead of storing the corrected values directly as a float. Moreover, if you have e.g. a Pearson matrix you need to calculate first the weight factors which is not that easy and needs additional computing time. Especially for high resolution matrices.
2.The files you provide on the ftp server show that you do not stick strictly to your own definition. I checked a few files and they have floating values for `matrix['count']` set and even worse the correction factors stored in 'bin['weight']' were present, but were all `NaN`. 

To make a long story short: Wouldn't it be better to change the default data type of `matrix['count']` to float32?

**Comment by nvictus** [comment]
> How strict is the usage of the datatypes you have defined? 

Not particularly strict at all! Especially for the `count` column.

> You can manipulate this by setting cooler._writer.COUNT_DTYPE 

This used to be the case. There is actually a `dtypes` option to explicitly specify data types in `cooler.io.create`. It isn't documented very clearly, and I've been working on replacing it with `columns` and `dtype` arguments that mimics the behavior of `pandas.read_csv`. This will allow overriding standard column dtypes and declaring non-standard columns.

> The usage of int32 as a datatype is a bit problematic because after a correction of a transformation of the data to obs/exp or pearson matrix we need float values and not integers. 

Yes, indeed! The rationale for making `count` integer by default was for the goal of losslessly storing the raw counts and applying transformations on top of them (e.g. storing multiple balancing vectors). Of course that's not always the case, and we definitely intend to support floating point as an alternative dtype for `count`, which can be done. 

Note that Cooler was also designed to support multiple value columns, so one could even store `count`, `balanced` and `obsexp` values next to one another, or do something even more exotic like grouping counts by strand orientation!

> For this case you have the field 'weight' in bins and the idea is to apply this weights to the int counts.

We plan on also storing "expected" vectors in a standard way in the file. The delay has come mostly from debating how to deal with the fact that we sometimes partition expected by chromosome arm rather than by chromosome. That also complicates the transformation.

> The files you provide on the ftp server show that you do not stick strictly to your own definition.

Yikes! I'll take a look at that. If you remember which ones were problematic, could you email me?

>  Wouldn't it be better to change the default data type of matrix['count'] to float32

I wouldn't change the default at this point, especially since we almost never stray from it (It is also suggested by the name "count"). However, I do think it should be trivially easy to set a different dtype.

One thing to possibly consider is making even the "count" column strictly optional. It is already possible to query alternative value columns using `Cooler.pixels(field='myfield')`.
