### ISSUE TITLE
Can I generate an unsymmetric cooler file for an unsymmetric matrix, and to illustrate the unsymmetric matrix by HiGlass?

### ISSUE THREAD

**Issue by chenweizhongUCSD** [mirnylab/cooler#119]
Dear Author,

I have a unsymmetric matrix to illustrate. But when I using cooler to generate .cool file, it always enforced the .cool into a symmetric matrix.

Can I generate an unsymmetric cooler file for an unsymmetric matrix, and to illustrate the unsymmetric matrix by HiGlass?

Best,

**Comment by nvictus** [comment]
There is experimental support for asymmetric matrices with homogeneous axes in the `asymmetric` branch. Feel free to try it and report any issues. Otherwise, it should be available in the next release.

To use it at the command line, you can use [cooler cload pairs](http://cooler.readthedocs.io/en/latest/cli.html#cooler-cload) for pair input, or [cooler load](http://cooler.readthedocs.io/en/latest/cli.html#cooler-load) for binned input, and include the `--asymmetric` flag. Note that it doesn't work for `cooler cload pairix` yet. See this [notebook](https://github.com/hms-dbmi/hic-data-analysis-bootcamp/blob/master/notebooks/00_intro_cooler-cli.ipynb).

It won't work immediately on HiGlass, because it would need to update its cooler dependency to be asymmetry-aware.  But you can inspect the matrices with `cooler show` or in python/jupyter to make sure they look as they should.

However, if your matrix if the genomic coordinates on the two axes of your map are not identical, that is not supported yet. I assume that's not your case, though?

**Comment by pkerpedjiev** [comment]
Is there a flag in the cooler file that indicates that it's asymmetric? HiGlass needs the `mirror_tiles` flag in the tileset info in order to determine if it's symmetric or not. I can add this to the hgtiles repo (https://github.com/pkerpedjiev/hgtiles/blob/master/hgtiles/cooler.py#L155) but just need a way to query the cooler file to see if it's asymmetric or not.

**Comment by nvictus** [comment]
Yeah, there will be a top-level `symmetric` attribute in the next format version.

**Comment by nvictus** [comment]
[Schema v3](https://cooler.readthedocs.io/en/latest/schema.html) as of cooler 0.8.0 now supports asymmetric matrices. At the command line, use the `--no-symmetric-upper` option for [cooler cload pairs](https://cooler.readthedocs.io/en/latest/cli.html#cooler-cload-pairs) or [cooler load](https://cooler.readthedocs.io/en/latest/cli.html#cooler-load).

**Comment by frankyan** [comment]
We used the cooler 0.7.10-dev asymmetric branch before. The generated non-symmetric mcool file can be correctly loaded by HiGlass. However, I updated to the latest version of cooler (0.8.5), the cooler v0.8.5 generated non-symmetric mcool file cannot be correctly loaded to HiGlass, which shows a symmetric heatmap in HiGlass. I think the problem might be caused by the new Schema v3 since version  0.8.0 which is not well supported by HiGlass.

**Comment by nvictus** [comment]
The PR for that support is here: https://github.com/higlass/clodius/pull/95

It should be in the next HiGlass release. I removed support for the 0.7.19-dev version you were testing before, but if you are still using such files, I'll restore it.

**Comment by frankyan** [comment]
Thanks. When will HiGlass release the next version?
There is another question in HiGlass view of non-symmetric matrix. The row of the HiGlass heatmap is "c2:p2" and column is "c1:p1". Is that correct? I think it's better to set row as "c1:p1" and column as "c2:p2". I also created an issue in HiGlass repo.
**https://github.com/higlass/higlass/issues/704#issue-459524186**
Since I don't know how to transpose the heatmap view of non-symmetric matrix in HiGlass, I tried to change the options `-c1 2 -p1 3 -c2 4 -p2 5` to `-c1 4 -p1 5 -c2 2 -p2 3`  in `cooler cload pairs` to make a "transposed" cool file. However, I found that it doesn't work. The view in HiGlass didn't change. And I used `cooler dump` on the `cool` files generated with the options `-c1 2 -p1 3 -c2 4 -p2 5` and `-c1 4 -p1 5 -c2 2 -p2 3` , the output pixels matrix files are the same. It seems that  `cooler cload pairs` doesn't use the `-c1`,  `-p1`, `-c2`, `-p2` options.

**Comment by nvictus** [comment]
>  It seems that cooler cload pairs doesn't use the -c1, -p1, -c2, -p2 options.

That's strange. Could you try the following on your base resolution cooler to transpose it:

```bash
cooler dump $INPUT_COOL \
    | awk 'BEGIN{OFS="\t"}{print $2,$1,$3}' \
    | cooler load -f coo -N <(cooler dump -t bins $INPUT_COOL) - $OUTPUT_COOL
```

**Comment by frankyan** [comment]
Hi, I tried your code (cooler v0.8.5). It works. The $OUTPUT_COOL was transposed. Is this the correct way to do transpose?
I think it's better to do transpose using options `-c1 4 -p1 5 -c2 2 -p2 3`.

**Comment by luoxun0213** [comment]
> > It seems that cooler cload pairs doesn't use the -c1, -p1, -c2, -p2 options.
> 
> That's strange. Could you try the following on your base resolution cooler to transpose it:
> 
> ```shell
> cooler dump $INPUT_COOL \
>     | awk 'BEGIN{OFS="\t"}{print $2,$1,$3}' \
>     | cooler load -f coo -N <(cooler dump -t bins $INPUT_COOL) - $OUTPUT_COOL
> ```

Hi Nezar, 

In order to present RNA as rows and DNA as columns in HiGlass, I also tried to transpose cool files using your code, and then `mcool` file is generated by `cooler zoomify`. However, when I visualize the `mcool` file through higlass, it is still opposite. Is there any way to transpose mcool files? The following are the versions of the relevant software,
```
- cooler=0.9.2
- higlass-docker=0.10.4
- cooltools=0.5.4
```

Best,

Xianglei
