### ISSUE TITLE
Apply correction factors

### ISSUE THREAD

**Issue by joachimwolff** [mirnylab/cooler#120]
Short question: Do you always expect to apply the correction factors on a matrix stored in `weight` `Corrected[i,j] = uncorrected[i,j] * weight[i] * weight[j]`? 

I found this on http://cooler.readthedocs.io/en/latest/api.html#cooler-ice 

Thanks a lot,

Joachim

**Comment by nvictus** [comment]
Hey, Joachim. Sorry this fell off my radar!

Yes, the weight factors are always applied multiplicatively when using `Cooler.matrix(balance=True)`.
I realized that the docstring has not been not updated, but note that you can pass any column name instead of `True` to use that as an alternate weight column, e.g. `Cooler.matrix(balance='custom_weight')`.

To make things more flexible, we have been discussing providing another option to register custom pixel transformations (in lieu of balance), along the lines of `Cooler.matrix(transform=custom_func)`. I'll create a new issue to start a discussion.
