### ISSUE TITLE
cooler dump KeyError

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [mirnylab/cooler#132]
Hi,
Could you please explain this error and fix for following error
```
cooler dump -b -t pixels -r chr3:10,000,000-12,000,000 -r2 chr17  DFF064KIG.multi.cool
```
KeyError: "Unable to open object (object 'chroms' doesn't exist)"

The .hic file was converted to cooler using https://github.com/4dn-dcic/hic2cool

**Comment by sergpolly** [comment]
Could you double check if you're dealing with the multi resolution cooler:
`cooler list DFF064KIG.multi.cool`
If that command gives you several lines like so: `DFF064KIG.multi.cool::5` etc, that means you're dealing with multires `cooler` and in order to perform the dump you'd need to specify particular resolution in that file using URI: `DFF064KIG.multi.cool::0` or in the newer version of `cooler` like so: `DFF064KIG.multi.cool::20kb`,
You can check what's inside of each URI using info command , i.e. `cooler info DFF064KIG.multi.cool::4`

**Comment by nvictus** [comment]
You need to provide a path to the resolution you want to query (separated by `::`). 
If you converted from hic, the paths will be named `resolution/<bp_size>`.

e.g. for 50kb:

```
cooler dump -b -t pixels -r  chr3:10,000,000-12,000,000 -r2 chr17  DFF064KIG.multi.cool::resolutions/50000
```

To see a list of resolutions inside the file, use `cooler list -l DFF064KIG.multi.cool`.

**Comment by tgreen41474** [comment]
Thanks for your responses.  Parul posted the original ticket for me.

I tried running 
`cooler info DFF064KIG.multi.cool`
and got the same message KeyError: "Unable to open object (object 'chroms' doesn't exist)"

`cooler list DFF064KIG.multi.cool`
did work and resulted in
DFF064KIG.multi.cool::/resolutions/100000
DFF064KIG.multi.cool::/resolutions/1000000
DFF064KIG.multi.cool::/resolutions/250000
DFF064KIG.multi.cool::/resolutions/2500000
DFF064KIG.multi.cool::/resolutions/50000
DFF064KIG.multi.cool::/resolutions/500000

`cooler dump -b -t pixels -r  chr3:10,000,000-12,000,000 -r2 chr17  DFF064KIG.multi.cool::resolutions/50000`
output 
Balancing weights not found

**Comment by tgreen41474** [comment]
Any suggestions on what is causing Unable to open object (object 'chroms' doesn't exist)?

**Comment by sergpolly** [comment]
Multi-resolution `cooler` is merely a "container" with several  `coolers` inside, each can be referred to using URI (e.g. `DFF064KIG.multi.cool::resolutions/50000`), and most of the CLI commands require `cooler` with a single resolution, so you need to provide a URI instead of the PATH in most cases.

`(object 'chroms' doesn't exist)` happens when you give a PATH to a multires `cooler` to a CLI command that expects a single resolution `cooler`, which you can refer to using URI.

As to the new error you are getting - it seems like you are requesting a dump of the balanced matrix (`-b` flag in the `dump` command), but none of the `coolers` inside of your multires `cooler` are balanced

**Comment by tgreen41474** [comment]
thanks for the response .  If I remove the -b I get 

ValueError: Unknown sequence label: chr3

**Comment by nvictus** [comment]
The hic file you converted may be using Ensembl style chromosome names. Check `cooler dump -t chroms`. In that case you use `1,2,3...X,Y,Mt` instead of `chr1,chr2,chr3,...,chrX,chrY,chrM`.

**Comment by nvictus** [comment]
To expand on Sergey's answer:

The `-b` option looks for a column in the bin table called `weight` to use for balancing. You can balance your individual coolers by running `cooler balance DFF064KIG.multi.cool::resolutions/<binsize>`, which will generate the normalization weight vector. If you want just the raw counts, drop the `-b` option.

Also, we need a friendlier error than `(object 'chroms' doesn't exist)` when an invalid URI is provided. I'll file an issue.

**Comment by tgreen41474** [comment]
thanks the info commands is now working
