### ISSUE TITLE
Question concerning balancing / correction

### ISSUE THREAD

**Issue by gtrichard** [mirnylab/cooler#140]
Dear all,

While using cool tools / HiGlass I came across the balancing of the matrices. In HiCExplorer we use the correction of the matrices you developed in 2012 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3816492/). I was wondering, how the two are differing since the goal seems to be the same, i.e. achieving equal visibility across all genomic regions / improving Hi-C data visualisation.

Also, I have a second question concerning the use of such corrected or balanced matrices for computation of Obs/Exp matrices. Are these corrections compatible with such a computation? Or should Obs/Exp matrices be computed only on raw matrices?

Best,
Gautier

**Comment by Phlya** [comment]
I can give a brief answer, perhaps people from the Mirny lab will elaborate afterwards.

balancing in cooler is the same as iterative correction from Imakaev 2012. Filtering of bad bins works in cooler differently, it is based on `MAD max` (see explanation in the `cooler balance -h`). Otherwise as far as I understand the procedure is the same.

Compatible, and expected should be computed from the balanced data.

**Comment by nvictus** [comment]
Thanks, @Phyla! That's all correct. The default in cooler is to do genome-wide iterative correction, but you can also store an additional vector of intra-chromosomal balancing weights with `--cis-only`.

Two cosmetic differences are:
* The "balancing weights" produced by cooler are the reciprocal of the "biases" as defined in Imakaev et al, 2012.
* By default, we rescale the weights so that the corrected marginals sum to unity.

As for Obs/Exp, we normally compute those on corrected data.
