### ISSUE TITLE
How to apply normalization factors

### ISSUE THREAD

**Issue by joachimwolff** [mirnylab/cooler#155]
Hi,

I am reading in a hic2cool [issue](https://github.com/4dn-dcic/hic2cool/issues/22) that hic2cool version 0.5 will use divisive correction factors. At the same time it seems that cooler itself still uses multiplicative weights. (See [hic2cool](https://github.com/4dn-dcic/hic2cool/blob/master/hic2cool/hic2cool_utils.py#L803)) and [my old issue](https://github.com/mirnylab/cooler/issues/120).
In the hic2cool issue it is stated that divisive correction factors are applied as follows: `corr_i,j = orig_i,j / corrfactor_i / corrfactor_j` but in the ICE publication it is  `corr_i,j = orig_i,j / corrfactor_i * corrfactor_j`:

> After the vector of biases is computed, the corrected map of relative contact probabilities is obtained by Tij = Oij/(BiBj) 

https://www.nature.com/articles/nmeth.2148

I am a bit confused now what is the old and what is the new way and if cool files produced by hic2cool really use divisive correction factors if all other cool files use multiplicative ones. 

I hope you can clarify this a bit.

Thanks a lot,

Joachim

**Comment by joachimwolff** [comment]
Given the latest answer from hic2cool: https://github.com/4dn-dcic/hic2cool/issues/24 we have now really the situation I feared: Some cool files have stored multiplicative some have divisive correction factors. Any idea how to solve this?

**Comment by nvictus** [comment]
All weights generated by `cooler balance` are multiplicative. It is the reciprocal of the biases as defined in the ICE paper. We decided on switching to this convention long ago.

Because of some miscommunication between us, hic2cool and HiGlass devs, the 4DN DCIC started converting hic files by extracting their divisive weights unmodified. Because of this behavior, these specific weights (named `KR`, `VC`, `VC_SQRT`) ended up being special-cased by HiGlass and treated as divisive. DCIC decided that it would be better to leave the behavior as such and make hic2cool do the same.

The solution will be to special-case those same 3 names in the `cooler.matrix` selector. This is ugly and unfortunate, but seems to be the only way to deal with the backwards compatibility of files already generated. If you apply weights yourself, you'll have to account for those 3 special cases.

I'll aim to have that implemented in the next release as well as an option to force weight application to be divisive or multiplicative as desired. How does that sound?

**Comment by joachimwolff** [comment]
Hi,

sorry for the delayed answer, I do apply the correction factors on my own and so far I am using the metadata information which tool and which version created the file to decide if it is divisive or multiplicative. It would be really helpful (as you suggested somewhere else if I remember correctly?) to add a field to the metadata if the correction factors are divisive or multiplicative.

Best,

Joachim
