### ISSUE TITLE
csort modifies input file

### ISSUE THREAD

**Issue by ezorita** [mirnylab/cooler#19]
I am trying to use `cooler csort ` (version `cooler==0.5.3`) without much success. My pairs file `pairs.txt` has the following format:
```
chr12   74054834        +       chr17   37101300        -
chr10   107716614       +       chr8    74236985        +
...
```
and the chromosome size file (`hg19_chromsizes.txt`):
```
chr1    249250621
chr10   135534747
...
```

When I run `cooler csort hg19_chromsizes.txt pairs.txt` I get the following output:
```
Enumerating chroms...
chr1	1
chr10	2
chr11	3
chr12	4
chr13	5
chr14	6
chr15	7
chr16	8
chr17	9
chr18	10
chr19	11
chr2	12
chr20	13
chr21	14
chr22	15
chr3	16
chr4	17
chr5	18
chr6	19
chr7	20
chr8	21
chr9	22
chrM	23
chrX	24
chrY	25
```
and after a few seconds my 14GB contact pairs file is converted into a useless 28 byte binary file, along with a new file `pairs.txt.tbi`, which I guess it's the failed attempt to index the former with tabix.

Did I misunderstand the usage of `cooler csort`? Why does it modify the input file?

Thanks!

**Comment by nvictus** [comment]
It seems that it was treating your input pairs file as if it were compressed and tried to gunzip it. `cooler csort` should accept uncompressed pairs files as well, so that's a bug.

Why the output path would end up being identical to the input path and be overwritten is weird and I couldn't reproduce it. The output path is supposed to have a `.sorted.gz` or `.sorted.txt.gz` appended to it. In any case, you can specify a different output path with the `--out` option (but don't use the same name as the input file, of course).

Could you try again with the fixes in the `develop` branch and reply if you still encounter problems?

**Comment by ezorita** [comment]
The last version in `develop` works smoothly. I tried the last commit in `master` and I wasn't able to reproduce the input replacement either -- the buggy version was the one provided by `pip install`.

btw, It would be useful to give `cooler` a version argument in order to ease the debugging process.

Thanks

Eduard

**Comment by nvictus** [comment]
Great! Absolutely right about the `--version` argument. Will open a new issue.

**Comment by nvictus** [comment]
Btw, note that the order of chromosomes listed in the chromsizes file you provide determines the global ordering in the contact matrix produced, e.g. you might prefer the more "aesthetic" ordering of `chr1-22,X,Y,M`.

**Comment by ezorita** [comment]
Indeed :)

Thanks!
