### ISSUE TITLE
Load only values within a distance

### ISSUE THREAD

**Issue by joachimwolff** [mirnylab/cooler#194]
Hi Nezar,

I checked the API but could not see anything like the following:

I want to load a csr-matrix per chromosome but only the values of the matrix which are within a distance of x from the main diagonal. All other values should be just 0. The solution with the current API is to load the matrix `cooler_file.matrix().fetch('chr1').tocsr()` and to drop all values which are `abs(bin_id1 - bin_id2) > distance`. This works quite well, however, I need the memory for all the pixels that I will drop immediately. If just one chromosome is loaded, the small time of the peak usage is not that important, however, I load ~20 chromosomes with 20 threads in parallel and have a peak usage of up to 30 GB. I think if only the values within the distance can be loaded this could be reduced to the half.

- Is there a way to load only the values I need with the current API?
- If not, is there the possibility this feature can be implemented?

Best,

Joachim

**Comment by nvictus** [comment]
To avoid a dense matrix completely, you can do the following:

```
clr.matrix(sparse=True).fetch('chr1').tocsr()
```

Note: in this sparse mode, balancing is only applied to nonzero pixels, so you don't get bad bins completely filled with NaNs. If that's not desired, I would set `balance=False` and apply the weights manually.

> If not, is there the possibility this feature can be implemented?

We have been working on a lazy interface for reading out a rectangular range query in chunks. A version of it exists privately in [cooltools](https://github.com/mirnylab/cooltools/blob/master/cooltools/lib/_query.py). It's more low-level, but we plan to eventually migrate something like this into cooler. We use it, for example, for sliding diamond [insulation score](https://github.com/mirnylab/cooltools/blob/master/cooltools/insulation.py#L76-L108) on each chromosome, dropping pixels beyond a distance, but in manageable-sized chunks. For insulation score, we switched to sparse logic (bincount instead of sum) to apply the algorithm piecewise. But, you can use such a mechanism for building a complete csr-matrix per chromosome and using more intuitive operations.

**Comment by joachimwolff** [comment]
Hi Nezar,

Thanks for your answer. 

Maybe my formulation was not accurate enough, I don't want to have a sparse instead of a dense matrix - I already use the method you described to get a csr matrix for the full chromosome. My goal is to get a sparse matrix for the full chromosome but only with data for interactions within a distance x from the main diagonal. To load the sparse, but complete chromosome leads already to quite high peaks in the memory usage. I guess I need to mention I am testing this with GM12878 primary+replicate sample from Rao 2014 which is to my knowledge a dataset with one of the highest read coverages. For chromosome 1 I have a peak usage of around 6 GB.

I am using: `matrix = cooler_file.matrix(balance=False, sparse=True).fetch(self.chrnameList[0]).tocsr()`

Concerning the second suggestion: I think I can implement a partial load too, however I was hoping that I don't need to write it. 

Best,

Joachim

**Comment by nvictus** [comment]
Hi Joachim,

I think I understand your problem. Because of the data storage layout, populating a sparse matrix with contacts within a distance from the diagonal requires a procedure where a larger amount of data is loaded and unwanted pixels are filtered out. Using a single call to `clr.matrix().fetch(chrom)` will pull out data from the entire chromosome into memory at once, which will cause a memory spike. 

To do this with a smaller memory footprint we have to break the query area into narrower horizontal stripes, filter them, and populate the sparse matrix one chunk at a time. The implementation in cooltools is low-level plumbing that could be hidden behind a more user-friendly API, and we are planning to migrate it into cooler as the building block for other complex 2D queries.

My recommendation for now would be to populate your full chromosome sparse matrix by loading a series of narrower pieces partitioned along bin1 using `clr.matrix(as_pixels=True)`.

I think something like this should work:

```python
lo, hi = clr.extent('chr1')
mat = coo_matrix((hi - lo, hi - lo))
for i0, i1 in cooler.util.partition(lo, hi, step):
    # fetch stripe
    pixels = clr.matrix(balance=False, as_pixels=True)[i0:i1, lo:hi]
    # filter
    pixels = pixels[(pixels['bin2_id'] - pixels['bin1_id']) < dist]
    # insert into sparse matrix
    mat[pixels['bin1_id'] - lo, pixels['bin2_id'] - lo] = pixels['count']
    mat[pixels['bin2_id'] - lo, pixels['bin1_id'] - lo] = pixels['count']
mat = mat.tocsr()
```

**Comment by joachimwolff** [comment]
Hi Nezar,

Thanks a lot! The source code could be adapted almost like it is, the coo_matrix needs to be replaced by the lil_matrix, but that's it.

```
lo, hi = cooler_file.extent(self.chrnameList[0])
dist = self.distance // cooler_file.binsize
step = (hi - lo) // 16
if step < 1:
    step = 1
mat = lil_matrix((hi - lo, hi - lo))
row = []
col = []
data = []
for i0, i1 in cooler.util.partition(lo, hi, step):
    # fetch stripe
    pixels = cooler_file.matrix(balance=False, as_pixels=True)[i0:i1, lo:hi]
    # filter
    pixels = pixels[(pixels['bin2_id'] - pixels['bin1_id']) < dist]
    # insert into sparse matrix
    
    mat[pixels['bin1_id'] - lo, pixels['bin2_id'] - lo] = pixels['count']
    mat[pixels['bin2_id'] - lo, pixels['bin1_id'] - lo] = pixels['count']
matrix = mat.tocsr()
del mat
```

This reduces the amount of memory from around 30 GB to 10 GB if 20 chromosomes are loaded in parallel.

Best,

Joachim
