### ISSUE TITLE
balance mcool

### ISSUE THREAD

**Issue by faryabib** [mirnylab/cooler#205]
Hi there,
We need to balance our mcool files before uploading into HiGlass. Is there any way to balance all the resolutions in a mcool besides iterating through them one at a time? 
thanks --

**Comment by nvictus** [comment]
There isn't a batch command in `cooler` itself, but you can use tools like `xargs` or gnu-parallel:

```bash
cooler ls {mcool file} | xargs -n1 cooler balance {balance args}
```

To do a dry run, you can do:

```
$ cooler ls test.2.mcool | xargs -n1 echo 'cooler balance'

cooler balance test.2.mcool::/resolutions/2
cooler balance test.2.mcool::/resolutions/4
cooler balance test.2.mcool::/resolutions/8
cooler balance test.2.mcool::/resolutions/16
cooler balance test.2.mcool::/resolutions/32
```

**Comment by nvictus** [comment]
Note that you can parallelize the balancing operation on each individual resolution as desired with the `-p` option, but running balancing on multiple resolutions in the same file in parallel is not recommended because HDF5 can run into race conditions when reading and writing concurrently on the same file.

**Comment by nvictus** [comment]
Did this work for you? Can the issue be closed?

**Comment by faryabib** [comment]
Hi Nezar,

It worked fine.
I wonder if there is a way to perform distance dependent normalization instead of ICE, which I believe is the only option in cooler?

Thanks,
Babak



---
R. Babak Faryabi

Sent from a mobile device, please excuse brevity and typos!

On Jun 27, 2020, at 10:45 AM, Nezar Abdennur <notifications@github.com> wrote:

﻿

Did this work for you? Can the issue be closed?

**Comment by nvictus** [comment]
Yes, we compute the distance normalization using `cooltools`. We don't yet have a standard place to store them inside the file though and higlass doesn't yet support it as a transform. The difficulty is mostly because we typically do distance normalization separately for chromosome arms, and other normalizations for interarm and regions and that is more complicated to encode as a single vector.
