### ISSUE TITLE
Observed over expected

### ISSUE THREAD

**Issue by Phlya** [mirnylab/cooler#22]
Hi, is it possible to efficiently create and store a simple observed over expected map in the same (or different) cooler file? I'd like to have one for data at 5 kb resolution, but a whole chromosome to compute it in dense format won't fit into memory...

**Comment by nvictus** [comment]
The approach with large maps is to compute the 1D expected profile in a memory-efficient way and use that to compute observed-over-expected on the fly. Here is a tentative implementation that does this:

https://gist.github.com/nvictus/466d6ec866e744c7bb4952b78125a3ca

The `observed_over_expected` wrapper gives the idea. You divide the queried window by the corresponding [toeplitz](https://en.wikipedia.org/wiki/Toeplitz_matrix) matrix of the expected profile. This only handles the simplest query case, but can be improved to handle the general case.

For now, the expected profile is stored in a separate tsv file. We haven't decided on how to store this in a standard way in the cooler file because in general we prefer to compute expected on chromosomal arms rather than whole chromosomes, which actually restricts where observed/expected is valid.

Feedback appreciated as always!

**Comment by Phlya** [comment]
Thanks! This is interesting. I like your approach!

I have actually just today figured out a way to calculate an expected matrix for a number of first diagonals in a memory-efficient way (through dia sparse format, which makes sense) and quite quickly. You can do it for all diagonals too of course, but then it stops being memory-efficient :( I didn't know about the `toeplitz` method and was constructing a matrix myself though... But with `toeplitz` it's even easier. So, for completeness, here is my option (don't know about speed or memory efficiency relative to your approach if you only need an expected map for a small region):

```
def make_expected_vals(cooler, Ndiags):
    vals = {}
    for chrom in list(cooler.chroms()[:]['name'])[:-1]:#remove the last chrY
        mat = cooler.matrix(balance=True, sparse=True).fetch(chrom)
        diags = scipy.sparse.triu(scipy.sparse.tril(mat, Ndiags), 0, 'dia')
        for i in range(Ndiags):
            if i not in vals:
                vals[i] = []
            arr = diags.data[i][diags.data[i]==diags.data[i]]
            vals[i].append([np.mean(arr), np.std(arr), arr.shape[0]])#Std in case we want to do z-score
    avals = []
    for d in vals:
        l = np.sum([i[2] for i in vals[d]])
        m = np.array([i[0]*i[2] for i in vals[d]]).sum()/l
        s = np.array([i[1]*i[2] for i in vals[d]]).sum()/l
        avals.append((m ,s))
    return np.array(avals)
```
Then `avals[:,0]` is used in `toeplitz` (and the other column from the array too, if we want z-scores).

I'm luckily working with mouse and don't have to worry about chromosomal arms...

**Comment by Phlya** [comment]
Just for future reference want to mention that Nezar's code gives better results for some reason - i.e. data appears much better normalized when comparing between samples, than with my code.

**Comment by nvictus** [comment]
Now implemented in [cooltools](https://github.com/mirnylab/cooltools/) expected. We may factor it back into cooler once we have agreed on a schema for "expected".
