### ISSUE TITLE
variable-step coarsening

### ISSUE THREAD

**Issue by Phlya** [mirnylab/cooler#81]
Is it possible to create a cooler from another cooler directly, but with different bins? Essentially, a generalized `coarsen`, but with new bins specified explicitly?

**Comment by nvictus** [comment]
Currently, no. It didn't seem worth the hassle doing something like fractional allocation of contacts when the new set of bins cuts into some of the old ones, since one could just start from pairs in the first place and do it properly.

But this is in principle easy if the new bin edges are a subset of the old ones. It would be a nice feature addition to `coarsen`.

**Comment by Phlya** [comment]
I don't think fractional allocation is a good idea, and if new boundaries are not a subset this should raise an error.

**Comment by nvictus** [comment]
Cooler coarsen now works with variable-sized bins.
