### ISSUE TITLE
Support for variable-sized bins with gaps

### ISSUE THREAD

**Issue by nvictus** [mirnylab/cooler#84]
Based on #80. This should raise an error for now, but we can support this if there are good use cases. Maybe 5C and capture-C.

**Comment by Phlya** [comment]
Other than 5C/capture, one can imagine some other cases where this could be the expected behavior: binning with fragment resolution and excluding some NNNNN regions, the use case I mentioned in the previous issue; also in some organisms (e.g. mouse) all or many chromosomes start with a big gap, so one might want to just have no bins for those areas, for example.

**Comment by nvictus** [comment]
Continue in #104
