### ISSUE TITLE
Interchromosomal interactions and multiple chromosome retrieval

### ISSUE THREAD

**Issue by joachimwolff** [mirnylab/cooler#95]
Dear cooler-Team,

if you call `cooler_file.matrix(balance=False, sparse=True).fetch(chr1, chr2)` you only get the intrachromosomal interactions of `chr1` and `chr2` but no interchromosomal interactions of `chr1` and `chr2`. Is this correct or am I doing a mistake? 

Furthermore, it is possible to retrieve the information of the interaction matrix for two chromosomes or regions but only one chromosome or region is possible if you want to retrieve the bins. It would be nice to retrieve the same number of chromosomes or regions as in `matrix().fetch()`.

And last, is it somehow possible to retrieve more than two e.g. `n`-chromosomes or regions with the `fetch` function? This would help a lot to improve the speed of my software and would increase the significance of the `cooler`-format.

Thanks a lot in advance,

Joachim

**Comment by nvictus** [comment]
Hi Joachim,

>  Is this correct or am I doing a mistake?

Are you sure you get intra-chromosomal (cis) data? It should return only inter-chromosomal (trans) between chr1 and chr2, unless chr1 and chr2 are the same. That is, `c.matrix().fetch(chr1, chr1)` is equivalent to `c.matrix().fetch(chr1)`. Please send me an example file if this is not the case.


> Furthermore, it is possible to retrieve the information of the interaction matrix for two chromosomes or regions but only one chromosome or region is possible if you want to retrieve the bins. It would be nice to retrieve the same number of chromosomes or regions as in matrix().fetch().

I'm not sure I fully understand, but maybe what you are looking for is `c.matrix(as_pixels=True, join=True)`. 

* Instead of a dense matrix or a sparse matrix, `as_pixels` will return a dataframe, but only containing data in the upper triangle of the contact matrix: for cis data, pixels are not repeated with their transpose as they would be in a matrix; and for trans data, if the (chr1, chr2) block contains data because chr1 comes before chr2, then the (chr2, chr1) block will not. If there is desire, I think the semantics for trans data could be changed so that both cases return data.

* The `join` option produces a relational join of bins against pixels, replacing `bin1_id` and `bin2_id` with columns in the bin table, suffixed with '1' and '2', respectively. Note that the `join` option is just a shortcut for using the `cooler.annotate` function, which can be used to assign any bin-level annotations to a table of pixels. You can see examples [here](https://nbviewer.jupyter.org/github/mirnylab/cooler-binder/blob/master/cooler_api.ipynb#Bin-annotation).

Note that you can pass also pass a bins selector instead of a dataframe.
```
annotated_pixels = cooler.annotate(c.bins(), mypixels)
```
Let me know if this solves your problem.

> is it somehow possible to retrieve more than two e.g. n-chromosomes or regions with the fetch function? 

Note that you can query the genome-wide contact matrix as one global 2D array using standard slice indexing, e.g. `c.matrix()[i0:i1, j0:j1]`. If you want to select contiguous blocks including multiple chromosomes or regions, you can get their offset positions with `c.offset(region)` or `c.extent(region)`. 

If they are not contiguous, can you give me a sense of how large `n` would be? We have ways to collect large collections of small snippets, but they are not currently in the cooler library.
